"""Explicit demo/mock market data, used ONLY when QVeris is not configured.

Every mock payload is clearly flagged with is_mock=True and surfaces as
`MOCK DATA` in the UI and reports. Numbers are illustrative, not real.
"""

from ..schemas.qveris import (
    CompanyProfile,
    DataPointMeta,
    MarketDataBundle,
    NewsItem,
    NormalizedFundamentals,
    NormalizedNews,
    NormalizedQuote,
)

_MOCK_COMPANIES: dict[str, dict] = {
    "AAPL": {
        "name": "Apple Inc.",
        "sector": "Technology",
        "industry": "Consumer Electronics",
        "description": "Designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and services worldwide.",
        "price": 228.50,
        "change_percent": 0.8,
        "volume": 48_000_000,
        "market_cap": 3_450_000_000_000,
        "revenue": 391_000_000_000,
        "net_income": 97_000_000_000,
        "free_cash_flow": 108_000_000_000,
        "eps": 6.42,
        "shares_outstanding": 15_100_000_000,
        "total_debt": 106_000_000_000,
        "cash": 65_000_000_000,
        "gross_margin": 0.46,
        "operating_margin": 0.31,
        "net_margin": 0.25,
        "roe": 1.47,
        "roic": 0.56,
        "revenue_growth_5y": 0.08,
        "pe_ratio": 35.6,
        "fcf_yield": 0.031,
        "debt_to_equity": 1.87,
        "news": [
            ("Services revenue reaches new record", "Recurring services segment keeps growing.", "positive"),
            ("Regulatory scrutiny on app store fees", "Antitrust pressure in several markets.", "negative"),
            ("New product cycle announced", "Refresh across the hardware lineup.", "neutral"),
        ],
    },
    "MSFT": {
        "name": "Microsoft Corporation",
        "sector": "Technology",
        "industry": "Software — Infrastructure",
        "description": "Develops and supports software, services, devices, and cloud solutions worldwide.",
        "price": 452.30,
        "change_percent": 0.4,
        "volume": 21_000_000,
        "market_cap": 3_360_000_000_000,
        "revenue": 245_000_000_000,
        "net_income": 88_000_000_000,
        "free_cash_flow": 74_000_000_000,
        "eps": 11.86,
        "shares_outstanding": 7_430_000_000,
        "total_debt": 97_000_000_000,
        "cash": 76_000_000_000,
        "gross_margin": 0.70,
        "operating_margin": 0.45,
        "net_margin": 0.36,
        "roe": 0.35,
        "roic": 0.29,
        "revenue_growth_5y": 0.14,
        "pe_ratio": 38.1,
        "fcf_yield": 0.022,
        "debt_to_equity": 0.36,
        "news": [
            ("Cloud segment grows double digits", "Enterprise cloud demand remains strong.", "positive"),
            ("AI infrastructure capex rises", "Heavy datacenter investment continues.", "neutral"),
        ],
    },
    "KO": {
        "name": "The Coca-Cola Company",
        "sector": "Consumer Defensive",
        "industry": "Beverages — Non-Alcoholic",
        "description": "Manufactures, markets, and sells nonalcoholic beverages worldwide.",
        "price": 63.10,
        "change_percent": -0.2,
        "volume": 12_000_000,
        "market_cap": 272_000_000_000,
        "revenue": 46_000_000_000,
        "net_income": 10_700_000_000,
        "free_cash_flow": 9_500_000_000,
        "eps": 2.47,
        "shares_outstanding": 4_310_000_000,
        "total_debt": 42_000_000_000,
        "cash": 13_000_000_000,
        "gross_margin": 0.60,
        "operating_margin": 0.29,
        "net_margin": 0.23,
        "roe": 0.42,
        "roic": 0.16,
        "revenue_growth_5y": 0.05,
        "pe_ratio": 25.5,
        "fcf_yield": 0.035,
        "debt_to_equity": 1.62,
        "news": [
            ("Pricing power holds through inflation", "Volume steady despite price increases.", "positive"),
            ("Health trends pressure sugary drinks", "Consumer preference shift continues.", "negative"),
        ],
    },
    "BRK.B": {
        "name": "Berkshire Hathaway Inc.",
        "sector": "Financial Services",
        "industry": "Insurance — Diversified",
        "description": "Diversified holding company engaged in insurance, freight rail, utilities, energy, and other businesses.",
        "price": 465.80,
        "change_percent": 0.1,
        "volume": 3_500_000,
        "market_cap": 1_000_000_000_000,
        "revenue": 371_000_000_000,
        "net_income": 43_000_000_000,
        "free_cash_flow": 30_000_000_000,
        "eps": 19.85,
        "shares_outstanding": 2_160_000_000,
        "total_debt": 125_000_000_000,
        "cash": 325_000_000_000,
        "gross_margin": 0.24,
        "operating_margin": 0.14,
        "net_margin": 0.12,
        "roe": 0.08,
        "roic": 0.07,
        "revenue_growth_5y": 0.06,
        "pe_ratio": 23.5,
        "fcf_yield": 0.030,
        "debt_to_equity": 0.21,
        "news": [
            ("Record cash pile keeps growing", "Management waits for attractive prices.", "neutral"),
        ],
    },
    "NVDA": {
        "name": "NVIDIA Corporation",
        "sector": "Technology",
        "industry": "Semiconductors",
        "description": "Designs graphics, compute, and networking platforms for gaming, datacenter, and automotive markets.",
        "price": 172.40,
        "change_percent": 2.1,
        "volume": 195_000_000,
        "market_cap": 4_200_000_000_000,
        "revenue": 130_000_000_000,
        "net_income": 73_000_000_000,
        "free_cash_flow": 61_000_000_000,
        "eps": 2.97,
        "shares_outstanding": 24_400_000_000,
        "total_debt": 10_000_000_000,
        "cash": 43_000_000_000,
        "gross_margin": 0.75,
        "operating_margin": 0.62,
        "net_margin": 0.56,
        "roe": 0.92,
        "roic": 0.75,
        "revenue_growth_5y": 0.64,
        "pe_ratio": 58.0,
        "fcf_yield": 0.015,
        "debt_to_equity": 0.13,
        "news": [
            ("Datacenter demand outpaces supply", "AI accelerator orders remain elevated.", "positive"),
            ("Competition in AI chips intensifies", "Custom silicon efforts by large customers.", "negative"),
        ],
    },
}

_GENERIC = {
    "name": None,  # filled with ticker
    "sector": "Unknown",
    "industry": "Unknown",
    "description": "Demo company generated from mock data because QVeris is not configured.",
    "price": 100.0,
    "change_percent": 0.0,
    "volume": 1_000_000,
    "market_cap": 10_000_000_000,
    "revenue": 5_000_000_000,
    "net_income": 500_000_000,
    "free_cash_flow": 450_000_000,
    "eps": 4.0,
    "shares_outstanding": 125_000_000,
    "total_debt": 1_500_000_000,
    "cash": 800_000_000,
    "gross_margin": 0.40,
    "operating_margin": 0.15,
    "net_margin": 0.10,
    "roe": 0.14,
    "roic": 0.11,
    "revenue_growth_5y": 0.06,
    "pe_ratio": 25.0,
    "fcf_yield": 0.045,
    "debt_to_equity": 0.60,
    "news": [
        ("No live news available", "QVeris is not configured; this is placeholder mock content.", "neutral"),
    ],
}

MOCK_TICKERS = list(_MOCK_COMPANIES.keys())


def _meta(symbol: str, note: str) -> DataPointMeta:
    return DataPointMeta(
        provider="mock",
        capability_id=None,
        source_timestamp=None,
        symbol=symbol,
        quality_notes=f"MOCK DATA — {note}. QVeris not configured; values are illustrative only.",
        is_mock=True,
    )


def get_mock_bundle(ticker: str) -> MarketDataBundle:
    symbol = ticker.upper().strip()
    raw = _MOCK_COMPANIES.get(symbol, {**_GENERIC, "name": f"{symbol} (Demo Company)"})
    name = raw["name"] or f"{symbol} (Demo Company)"

    quote = NormalizedQuote(
        symbol=symbol,
        price=raw["price"],
        change_percent=raw["change_percent"],
        volume=raw["volume"],
        market_cap=raw["market_cap"],
        meta=_meta(symbol, "quote"),
    )
    profile = CompanyProfile(
        symbol=symbol,
        name=name,
        sector=raw["sector"],
        industry=raw["industry"],
        description=raw["description"],
        meta=_meta(symbol, "company profile"),
    )
    fundamentals = NormalizedFundamentals(
        symbol=symbol,
        revenue=raw["revenue"],
        net_income=raw["net_income"],
        free_cash_flow=raw["free_cash_flow"],
        eps=raw["eps"],
        shares_outstanding=raw["shares_outstanding"],
        total_debt=raw["total_debt"],
        cash=raw["cash"],
        gross_margin=raw["gross_margin"],
        operating_margin=raw["operating_margin"],
        net_margin=raw["net_margin"],
        roe=raw["roe"],
        roic=raw["roic"],
        revenue_growth_5y=raw["revenue_growth_5y"],
        pe_ratio=raw["pe_ratio"],
        fcf_yield=raw["fcf_yield"],
        debt_to_equity=raw["debt_to_equity"],
        meta=_meta(symbol, "fundamentals"),
    )
    news = NormalizedNews(
        symbol=symbol,
        items=[NewsItem(title=t, summary=s, sentiment=sent, source="mock") for t, s, sent in raw["news"]],
        meta=_meta(symbol, "news"),
    )
    return MarketDataBundle(quote=quote, profile=profile, fundamentals=fundamentals, news=news, is_mock=True)
